service: converter-backend

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
  profile: serverless-admin
  versionFunctions: false
  memorySize: 128
  region: us-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource:
        Fn::GetAtt:
          - ExchangeRatesTable
          - Arn
custom:
  environment: ${file(.env.yml):${self:provider.stage}, file(.env.yml):default}

functions:
  updateExchangeRates:
    handler: lambda/updateExchangeRatesCache.updateExchangeRatesCache
    environment:
      FIXER_API_KEY: ${self:custom.environment.FIXER_API_KEY}
    name: ${self:provider.stage}-updateExchangeRatesCache
    description: 'Updates the latest exchange rates from fixer and stores them in ExchangeRatesTable, triggered hourly'
    events:
      - schedule:
          name: updateExchangeRatesCacheHourly
          description: 'Triggers the updateExchangeRatesCache function hourly, to update the exchange rates and cache them in ExchangeRatesTable'
          rate: rate(1 hour)
  updateCurrencySymbolsCache:
    handler: lambda/updateCurrencySymbolsCache.updateCurrencySymbolsCache
    environment:
      FIXER_API_KEY: ${self:custom.environment.FIXER_API_KEY}
    name: ${self:provider.stage}-updateCurrencySymbolsCache
    description: 'Updates the currency symbols cache in ExchangeRatesTable'
    events:
      - schedule:
          name: updateCurrencySymbolsCache
          description: 'Triggers the updateCurrencySymbolsCache function every 6 hours.'
          rate: rate(6 hours)
  getCachedData:
    handler: lambda/getCachedData.getCachedData
    name: ${self:provider.stage}-getCachedData
    description: 'Gets the exchange rates from ExchangeRatesTable'
    events:
      - http:
          path: /exchangerates
          method: get
          cors: true

resources:
  Resources:
    ExchangeRatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ExchangeRatesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
