service: converter-backend

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10
  versionFunctions: false
  memorySize: 128
  region: us-east-1
  logRetentionInDays: 30
  environment:
    FIXER_API_KEY: ${env:FIXER_API_KEY, file(.env.yml):FIXER_API_KEY}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource:
        Fn::GetAtt:
          - ExchangeRatesTable
          - Arn

functions:
  updateExchangeRates:
    handler: lambda/updateExchangeRatesCache.updateExchangeRatesCache
    name: ${self:provider.stage}-updateExchangeRatesCache
    description: 'Updates the latest exchange rates from fixer and stores them in ${self:provider.stage}-ExchangeRatesTable, triggered hourly'
    events:
      - schedule:
          name: ${self:provider.stage}-updateExchangeRatesCacheHourly
          description: 'Triggers the ${self:provider.stage}-updateExchangeRatesCache function hourly, to update the exchange rates and cache them in ${self:provider.stage}-ExchangeRatesTable'
          rate: rate(1 hour)
  updateCurrencySymbolsCache:
    handler: lambda/updateCurrencySymbolsCache.updateCurrencySymbolsCache
    name: ${self:provider.stage}-updateCurrencySymbolsCache
    description: 'Updates the currency symbols cache in ${self:provider.stage}-ExchangeRatesTable'
    events:
      - schedule:
          name: ${self:provider.stage}-updateCurrencySymbolsCache
          description: 'Triggers the ${self:provider.stage}-updateCurrencySymbolsCache function every 6 hours.'
          rate: rate(6 hours)
  getCachedData:
    handler: lambda/getCachedData.getCachedData
    name: ${self:provider.stage}-getCachedData
    description: 'Gets the exchange rates from ${self:provider.stage}-ExchangeRatesTable'
    events:
      - http:
          path: /${self:provider.stage}-exchangerates
          method: get
          cors: true

resources:
  Resources:
    ExchangeRatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-ExchangeRatesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
